### ISSUE TITLE
Change falsey to falsy

### ISSUE THREAD

**Issue by timgivois** [chantastic/reactpatterns.com#1]
It's more common to see `falsy` in other common libraries like [Jest](https://jestjs.io/docs/en/using-matchers#truthiness). I believe that it should be changed for new programmers and specially those that don't have a good level of English as `falsy` and `falsey` could be confusing.

**Comment by chantastic** [comment]
Thanks @timgivois! Fixed now.

I honestly have no idea why I spelled it that way 🤦‍♂️
